// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go

// Package payments is a generated GoMock package.
package payments

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockPayer is a mock of Payer interface
type MockPayer struct {
	ctrl     *gomock.Controller
	recorder *MockPayerMockRecorder
}

// MockPayerMockRecorder is the mock recorder for MockPayer
type MockPayerMockRecorder struct {
	mock *MockPayer
}

// NewMockPayer creates a new mock instance
func NewMockPayer(ctrl *gomock.Controller) *MockPayer {
	mock := &MockPayer{ctrl: ctrl}
	mock.recorder = &MockPayerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockPayer) EXPECT() *MockPayerMockRecorder {
	return m.recorder
}

// Authorize mocks base method
func (m *MockPayer) Authorize(ctx context.Context, req *AuthorizeReq) (*Transaction, error) {
	ret := m.ctrl.Call(m, "Authorize", ctx, req)
	ret0, _ := ret[0].(*Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Authorize indicates an expected call of Authorize
func (mr *MockPayerMockRecorder) Authorize(ctx, req interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authorize", reflect.TypeOf((*MockPayer)(nil).Authorize), ctx, req)
}

// Void mocks base method
func (m *MockPayer) Void(ctx context.Context, req *VoidReq) (*Transaction, error) {
	ret := m.ctrl.Call(m, "Void", ctx, req)
	ret0, _ := ret[0].(*Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Void indicates an expected call of Void
func (mr *MockPayerMockRecorder) Void(ctx, req interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Void", reflect.TypeOf((*MockPayer)(nil).Void), ctx, req)
}

// Capture mocks base method
func (m *MockPayer) Capture(ctx context.Context, req *CaptureReq) (*Transaction, error) {
	ret := m.ctrl.Call(m, "Capture", ctx, req)
	ret0, _ := ret[0].(*Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Capture indicates an expected call of Capture
func (mr *MockPayerMockRecorder) Capture(ctx, req interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Capture", reflect.TypeOf((*MockPayer)(nil).Capture), ctx, req)
}

// Refund mocks base method
func (m *MockPayer) Refund(ctx context.Context, req *RefundReq) (*Transaction, error) {
	ret := m.ctrl.Call(m, "Refund", ctx, req)
	ret0, _ := ret[0].(*Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Refund indicates an expected call of Refund
func (mr *MockPayerMockRecorder) Refund(ctx, req interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refund", reflect.TypeOf((*MockPayer)(nil).Refund), ctx, req)
}
